#!/bin/bash -eux
cd "$(readlink --canonicalize "$(dirname "$0")")"
docker build . --tag trex
exec docker run \
  --interactive \
  --tty \
  --rm \
  --name trex \
  --hostname trex \
  --privileged \
  --cap-add=ALL \
  --security-opt seccomp=unconfined \
  --volume /sys/bus/pci/drivers:/sys/bus/pci/drivers:rw \
  --volume /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages:rw \
  --volume /sys/devices/system/node:/sys/devices/system/node:rw \
  --workdir /tmp/trex \
  trex
